language: node_js
node_js:
  - '12'
script:
  - npm run react-ui-install
  - npm run build
  - npm run test
deploy:
  provider: heroku
  app: lileavetracker
  on: master
  skip_cleanup: true
  api_key:
    secure: DxdeLCovCYNsLZH1J4iF02UiPapKm77vP2VoM1BhZ7o5tysXJhJW/QUjkyVlXGsiKcL5jR30tWCEAwFSxemDf5+8icZrRbBfZDWwq2Y6YvqNiH9KYa8+8Zihv4JjdeUSRQO8eY7xNvLCUneSCzFmz+VsbiTfqlcizkuIW23oW1LjcPH7S3XV5B7peE6xIjkvZ2O11LrdLAYB48mV+XOdtFlJzbG7FgWBPyrxEoj4tZO/41iSB0V/pC95XYPQQ0KPBUm5pl8zKczSD8DubyL4aqU7vVT86ph3imUmwBCU+n6U2/Vqfz9D++PWffXtId2+yZTGU76SqBZz6SSqbdudILeJDYAomAM+qzpauC/exbcdYGpCA/OUh2XbvvYamT6uHTuNH6C8A9UmCp3Pk5SJShVId/LIwcqnnryxCUWfefKlteuBUO1oFWUkS8Cn2am073M7oiyEWSrAMtUHkZr/Aq4ZfLBopcegCTO5almAtLuDI7NmoEctq2vmuBFs08bIqrJbm7KUMg6ikH1XjPBEQnCNXzWvcY3qfzUH2x7Ityv5b7Jxsjr3FGGuhwurvODp398dFFEz5272r2EGSR14birZ/GUuRjaGezfMV8HLPrGF+/boHZcJyNeIvuWebb6TqrQI2EoLxN+xG5aWYNsTRMGPm27Wa0TNTKpqmoTTYxQ=
